//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageStudents.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHANVIEN
    {
        public string ID { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string CCCD { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public byte[] HINHANH { get; set; }
        public string IDPB { get; set; }
    }
}
